# Generated by Django 4.2.16 on 2024-11-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('killmail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('killmail_time', models.DateTimeField()),
                ('solar_system_id', models.IntegerField()),
                ('moon_id', models.IntegerField(blank=True, null=True)),
                ('war_id', models.IntegerField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('position_z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kill_killmail',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_id', models.IntegerField(blank=True, null=True)),
                ('character_id', models.IntegerField(blank=True, null=True)),
                ('corporation_id', models.IntegerField(blank=True, null=True)),
                ('faction_id', models.IntegerField(blank=True, null=True)),
                ('damage_taken', models.IntegerField()),
                ('ship_type_id', models.IntegerField()),
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='killstory.killmail')),
            ],
            options={
                'db_table': 'kill_victim',
            },
        ),
        migrations.CreateModel(
            name='VictimItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_id', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('quantity_destroyed', models.BigIntegerField(blank=True, null=True)),
                ('quantity_dropped', models.BigIntegerField(blank=True, null=True)),
                ('singleton', models.IntegerField()),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='killstory.victim')),
            ],
            options={
                'db_table': 'kill_victim_item',
            },
        ),
        migrations.CreateModel(
            name='VictimContainedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_id', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('quantity_destroyed', models.BigIntegerField(blank=True, null=True)),
                ('quantity_dropped', models.BigIntegerField(blank=True, null=True)),
                ('singleton', models.IntegerField()),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_items', to='killstory.victimitem')),
            ],
            options={
                'db_table': 'kill_victim_contained_item',
            },
        ),
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_id', models.IntegerField(blank=True, null=True)),
                ('character_id', models.IntegerField(blank=True, null=True)),
                ('corporation_id', models.IntegerField(blank=True, null=True)),
                ('faction_id', models.IntegerField(blank=True, null=True)),
                ('damage_done', models.IntegerField()),
                ('final_blow', models.BooleanField()),
                ('security_status', models.FloatField()),
                ('ship_type_id', models.IntegerField()),
                ('weapon_type_id', models.IntegerField()),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='killstory.killmail')),
            ],
            options={
                'db_table': 'kill_attacker',
            },
        ),
    ]
